### PR TITLE
Add stream insertion function for this:  cout << event << endl;

### PR DESCRIPTION
**Pull request by imsdigital**
This change tidies up the NONBLOCK change a little but also adds a stream insertion function
so the events can be sent to stdout when debugging.

### CODE REVIEW

**Comment by imsdigital** [comment]
Thank you Drew.

I have been using git for years but am fairly new to github.  After you merged my changes, how do I merge back into mine or is that unnecessary because my fork is now identical to yours?

Steve

**Comment by drewnoakes** [comment]
Thanks for the PRs.

Kinda depends how your repo is set up. If you have remotes for both your fork and this project, it's not too bad. Let's assume on your local machine your repo is called 'origin' and mine's called 'upstream' (a common convention).

If that's the case:

```
# get latest from upstream
git fetch upstream
# get on the master branch
git checkout master
# move your master branch to the upstream's master (this will undo any changes! be careful!)
git reset --hard upstream/master
# force push upstream's master to your origin master, getting everything in sync
git push --force origin/master
```

If you don't have upstream, do something like:

```
git remote add upstream git@github.com:drewnoakes/joystick.git
```

**Comment by imsdigital** [comment]
Hi

No problem with the pr, my pleasure.

Hmm .. I thought it would be on the gui.  Maybe it is easier to just fork again.

Steve

**Comment by imsdigital** [comment]
Ahh .. I figured it out.  I should have created a new branch and made my changes on that instead.

Steve

**Pull request merged**
